// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76qhJyQx1a5CeCzfK-ekheieKXlO8Xc8',
    appId: '1:153012586460:web:64cf09c11843403d1ef119',
    messagingSenderId: '153012586460',
    projectId: 'pfavf-cca51',
    authDomain: 'pfavf-cca51.firebaseapp.com',
    storageBucket: 'pfavf-cca51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5L2wUAZFTgkw3opRvmqGiScY3ArZZMM8',
    appId: '1:153012586460:android:f2a9fe7d4fd5fccf1ef119',
    messagingSenderId: '153012586460',
    projectId: 'pfavf-cca51',
    storageBucket: 'pfavf-cca51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeaWBbFw510P9vZzaCWraP6YMc8vHLm44',
    appId: '1:153012586460:ios:e88976012ac23d7c1ef119',
    messagingSenderId: '153012586460',
    projectId: 'pfavf-cca51',
    storageBucket: 'pfavf-cca51.appspot.com',
    iosBundleId: 'com.example.pfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeaWBbFw510P9vZzaCWraP6YMc8vHLm44',
    appId: '1:153012586460:ios:c4dee7d24af530901ef119',
    messagingSenderId: '153012586460',
    projectId: 'pfavf-cca51',
    storageBucket: 'pfavf-cca51.appspot.com',
    iosBundleId: 'com.example.pfa.RunnerTests',
  );
}
